MGC/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='mgc'),
    #path('configuracoes/', views.configuracoes, name='configuracoes'),

    # path('processos/', views.processos, name='processos'),
    # path('processos/adicionar/', views.processos_add, name='processos_add'),
    # path('processos/adicionar/licon', views.licitacao_request, name='licitacao_request'),
    # path('processos/editar/<int:processo_pk>', views.processos_edit, name='processo_edit'),
    # path('processos/deletar/<int:processo_pk>', views.processos_delet, name='processo_delet'),

    path('contratos/', views.contratos, name='contratos'), #VISUALIZAR TODOS OS CONTRATOS
    # path('contratos/adicionar/<int:processo_pk>/', views.contratos_add, name='contratos_add'),
    path('contratos/addsaldosec/<int:contrato_pk>/', views.contratos_addsaldosec, name='contrato_addsaldo'),
    path('contratos/additens/<int:contrato_pk>/', views.contratos_additens, name='contratos_additens'),
    # path('contratos/anexarof/<int:contrato_pk>/', views.contrato_enviar, name='contrato_enviar'), #ADAPTAR PARA ORDENS/ANEXAR
    # path('contratos/editar/<int:contrato_pk>', views.contrato_edit, name='contrato_edit'),
    # path('contratos/deletar/<int:contrato_pk>', views.contrato_delet, name='contrato_delet'),

    path('contratos/ordens/', views.ordens, name='ordens'),
    path('contratos/ordens/detalhes/<int:saldodetalhes_pk>/', views.saldo_detalhes, name='saldo_detalhes'),
    path('contratos/ordens/detalhes/<int:saldodetalhes_pk>/emitir', views.of_emitir, name='of_emitir'),

    path('contratos/ordens/detalhes/<int:saldoof_pk>/<int:of_log_pk>', views.of_log_delet, name='of_log_delet'),
    path('contratos/ordens/editar/<int:saldoof_pk>', views.of_edit, name='of_edit'),
    #path('contratos/ordens/deletar/<int:saldoof_pk>', views.of_delet, name='of_delet'),

    path('contratos/fiscal/', views.painelfiscal, name='painelfiscal'),

    path('contratos/adicionar', views.add_contratos, name='add_contratos'),
    path('contratos/editar/<int:contrato_id>', views.edit_contrato, name='edit_contrato'),
    path('contratos/request', views.contratos_request, name='contratos_request'),
    path('contratos/resquest/processar', views.processar_contratos_selecionados, name='processar_contratos_selecionados'),

    path('fornecedor/editar/<int:saldocontratosec_id>', views.confirmar_fornecedor, name='confirmar_fornecedor'),

    path('saldosec/<int:saldocontratosec_id>/exportar_excel/', views.exportar_excel_saldo, name='exportar_excel_saldo'),

    path('emitirof', views.emitirOF, name='emitirof'),

    #### HTMX ###########

    path('contratosbase/', views.contratos_base, name='contratos_base'),

    
    
]

MGPROTOCOLO/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.processos_no_setor, name='protocolo_inicial'),
    path('processos/no-setor/', views.processos_no_setor, name='processos_no_setor'),
    path('processos/encaminhados/', views.processos_encaminhados_pelo_setor, name='processos_encaminhados_pelo_setor'),
    path('processos/<int:processo_id>/', views.detalhes_processo, name='detalhes_processo'),
    path('processos/criar/', views.criar_processo, name='criar_processo'),
    path('processos/editar/<int:processo_id>/', views.editar_processo, name='editar_processo'),
    path('processos/<int:processo_id>/documentos/criar/', views.criar_documento, name='criar_documento'),
    path('processos/<int:processo_id>/maisinformacoes/', views.mais_informacoes, name='mais_informacoes'),
    
    path('movimentacoes/<int:processo_id>/criar/', views.criar_movimentacao, name='criar_movimentacao'),
    path('movimentacoes/tramitacao/', views.listar_movimentacoes_tramitacao, name='listar_movimentacoes_tramitacao'),

    path('processo/<int:processo_id>/receber/', views.receber_processo, name='receber_processo'),
    path('processo/<int:processo_id>/arquivar/', views.arquivar_processo, name='arquivar_processo'),
    path('processos-arquivados/', views.processos_arquivados, name='processos_arquivados'),

    path('protocolos/gerar/', views.gerar_protocolo, name='gerar_protocolo'),
    path('protocolos/', views.listar_protocolos, name='listar_protocolos'),
    path('protocolos/<int:protocolo_id>/comprovacao/', views.anexar_comprovacao, name='anexar_comprovacao'),
    path('protocolos/<int:protocolo_id>/comprovacao/visualizar/', views.visualizar_comprovacao, name='visualizar_comprovacao'),

    path('processo/<int:processo_id>/corrigir/', views.historico_correcoes_processo, name='historico_correcoes_processo'),
    path('processo/<int:processo_id>/corrigir/salvar/', views.salvar_correcoes_processo, name='salvar_correcoes_processo'),

    path('sugerir-dados-processo/', views.sugerir_descricao_processo, name='sugerir_dados_processo'),

    path('historico_tramitacoes/<int:processo_id>/gerar/', views.gerar_historico_tramitacoes, name='gerar_historico_tramitacoes'),
]

SGI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('HOME.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('gestaocontratos/',include('MGC.urls')),
    path('combustiveis/',include('MGCOMBUSTIVEIS.urls')),
    path('regularidadefiscal/',include('MGREGULARIDADEFISCAL.urls')),
    path('protocolo/',include('MGPROTOCOLO.urls')),
    path('transparencia/',include('MGTRANSPARENCIA.urls')),
    path('comunicacao/',include('MGCOMUNICACAO.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MGPROTOCOLO/models.py
from datetime import date
import os
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError
from HOME.models import Setor as SetorHome
from HOME.models import Secretaria as SecretariaHome

def diretorioDocumento (instance, filename):
    extensao = os.path.splitext(filename)[1]
    filename = filename.replace("/","-")[:10]
    filename = '{}.{}'.format(filename,extensao)
    return f'MGPROTOCOLO/documentos/{instance.processo.criado_em.year}/{instance.processo.demandante.nome}/{filename}'

def diretorioProtocolo (instance, filename):
    extensao = os.path.splitext(filename)[1]
    return f'MGPROTOCOLO/protocolos/{instance.criado_em.year}/{instance.destinatario.nome}/{instance.criado_em} por {instance.criado_por.username} - id {instance.id}{extensao}'

class Processo(models.Model):
    STATUS_CHOICES = [
        ('em_analise', 'Em análise'),
        ('concluido', 'Concluído'),
        ('cancelado', 'Cancelado'),
        ('arquivado', 'Arquivado'),
    ]

    MODALIDADE_CHOICES = [
        ('digital', 'Digital'),
        ('fisico', 'Físico'),
    ]

    numero = models.CharField(max_length=100, unique=True, db_index=True, null=True, blank=True)
    titulo = models.CharField(max_length=255, null=True, blank=True)
    descricao = models.TextField(blank=True, null=True)
    criado_por = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    demandante = models.ForeignKey(SetorHome, on_delete=models.SET_NULL, null=True, blank=True, related_name='SetorDemandante')
    fim = models.ForeignKey(SetorHome, on_delete=models.SET_NULL, null=True, blank=True, related_name='SetorFim')
    atual = models.ForeignKey(SetorHome, on_delete=models.SET_NULL, null=True, blank=True, related_name='SetorAtual')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='em_analise', null=True, blank=True)
    prazo = models.DateField(blank=True, null=True)
    criado_em = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    atualizado_em = models.DateTimeField(auto_now=True, null=True, blank=True)
    ultima_movimentacao = models.ForeignKey('Movimentacao', on_delete=models.SET_NULL, null=True, blank=True, related_name='processo_ultima_movimentacao')
    ativo = models.BooleanField(default=True)
    modalidade = models.CharField(max_length=15,choices=MODALIDADE_CHOICES, default='fisico')
    
    def __str__(self):
        return f"{self.numero} - {self.titulo}"

    def clean(self):
        if self.demandante == self.fim:
            raise ValidationError("O setor demandante não pode ser o mesmo que o setor responsável.")
        
    def validate_unique(self, exclude=None):
        super().validate_unique(exclude)
        # Verifica se já existe outro processo com o mesmo número
        if Processo.objects.filter(numero=self.numero).exclude(pk=self.pk).exists():
            raise ValidationError({'numero': "Já existe um processo com esse número."})

    def esta_ativo(self):
        """
        Retorna True se o processo estiver ativo, False caso contrário.
        """
        return self.ativo

    def tempo_restante(self):
        """
        Retorna o número de dias restantes para o prazo do processo.
        Se o prazo já passou, retorna None.
        """
        if self.prazo:
            dias_restantes = (self.prazo - date.today()).days
            return max(dias_restantes, 0) if dias_restantes > 0 else None
        return None
    
    def resumo_movimentacoes(self):
        """
        Retorna um resumo das movimentações do processo.
        """
        resumo = []
        for movimentacao in self.movimentacoes.all():
            resumo.append({
                'realizado_em': movimentacao.realizado_em.strftime('%d/%m/%Y %H:%M'),
                'realizado_por': movimentacao.realizado_por.get_full_name(),
                'remetente': movimentacao.remetente.nome,
                'destinatario': movimentacao.destinatario.nome,
                'status': movimentacao.get_status_display(),
                'confirmacao': movimentacao.confirmacao,
                'confirmado_em': movimentacao.confirmado_em.strftime('%d/%m/%Y %H:%M'),
                'confirmado_por': movimentacao.confirmado_por.get_full_name(),
            })
        return resumo
    
    def esta_em_atraso(self):
        """
        Retorna True se o prazo do processo já passou, False caso contrário.
        """
        if self.prazo:
            return date.today() > self.prazo
        return False

    def total_documentos(self):
        """
        Retorna o número total de documentos associados ao processo.
        """
        return self.documentos.count()
    
    def setores_envolvidos(self):
        """
        Retorna uma lista de todos os setores envolvidos no processo.
        """
        setores = set()
        for movimentacao in self.movimentacoes.all():
            setores.add(movimentacao.remetente.nome)
            if self.atual!= None:
                setores.add(movimentacao.destinatario.nome)
            else:
                setores.add('Arquivo')
        return list(setores)

    @classmethod
    def processos_no_setor(cls, setor):
        """
        Retorna os processos cuja última movimentação está no setor especificado.
        """
        return cls.objects.filter(atual__in=setor).order_by('-atualizado_em')

    @classmethod
    def processos_encaminhados_pelo_setor(cls, setor):
        """
        Retorna os processos que foram encaminhados pelo setor especificado para outros setores.
        """
        return cls.objects.filter(movimentacoes__remetente__in=setor).distinct()
    
    def usuario_pode_modificar(self, usuario):
        """
        Verifica se o usuário pertence ao setor atual do processo.
        """
        return usuario in self.atual.usuarios.all() if self.atual else False
    
    def arquivar(self):
        """ Define o processo como arquivado """
        self.status = 'arquivado'
        self.atual = None  # Remove o setor atual, pois foi arquivado
        self.save()

class Documento(models.Model):
    TIPO_CHOICES = [
        ('inicial', 'Documento Inicial'),
        ('complementar', 'Documento Complementar'),
    ]

    CLASSIFICACAO_CHOICES = [
        ('oficio', 'Ofício'),
        ('ci', 'Comunicado Interno'),
        ('despacho', 'Despacho'),
        ('memorando', 'Memorando'),
        ('parecer', 'Parecer'),
        ('portaria', 'Portaria'),
        ('laudo', 'Láudo'),
        ('relatorio', 'Relatório'),
        ('contrato', 'Contrato'),
        ('edital', 'Edital'),
        ('cotacoes', 'Cotações'),
        ('outros', 'Outros'),
    ]

    processo = models.ForeignKey(Processo, on_delete=models.CASCADE, related_name='documentos', null=True, blank=True)
    descricao = models.CharField(max_length=255, null=True, blank=True)
    classificacao = models.CharField(max_length=100, choices=CLASSIFICACAO_CHOICES, null=True, blank=True)
    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES, default='inicial', null=True, blank=True)
    arquivo = models.FileField(upload_to=diretorioDocumento, null=True, blank=True)
    criado_por = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    criado_em = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.descricao

class Movimentacao(models.Model):
    STATUS_CHOICES = [
        ('em_tramitacao', 'Em tramitação'),
        ('recebida', 'Recebida'),
        ('arquivada', 'Arquivada')
    ]

    RECEBIMENTO_CHOICES = [
        ('pendente', 'Pendente'),
        ('manual', 'Manual'),
        ('sistema', 'Sistema'),
    ]

    processo = models.ForeignKey(Processo, on_delete=models.PROTECT, related_name='movimentacoes', null=True, blank=True)
    descricao = models.TextField(null=True, blank=True)
    realizado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    realizado_em = models.DateTimeField(auto_now_add=True, db_index=True, null=True, blank=True)
    remetente = models.ForeignKey(SetorHome, on_delete=models.PROTECT, related_name='SetorRemetente', null=True, blank=True)
    destinatario = models.ForeignKey(SetorHome, on_delete=models.PROTECT, related_name='SetorDestinatario', null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='em_tramitacao', null=True, blank=True)
    confirmacao = models.CharField(max_length=20, choices=RECEBIMENTO_CHOICES, default='pendente', null=True, blank=True)
    confirmado_em = models.DateTimeField(null=True, blank=True)
    confirmado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, related_name='movimentacoes_confirmadas')
    observacoes = models.TextField(blank=True, null=True)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        if self.status != 'arquivada':
            return f"Movimentação de {self.processo.numero} para {self.destinatario.nome} realizada por {self.realizado_por}"
        else:
            return f"Movimentação para arquivo do {self.processo.numero} realizada por {self.realizado_por}"

    def clean(self):
        if self.remetente == self.destinatario:
            raise ValidationError("O setor de origem não pode ser o mesmo que o setor de destino.")
        
        if self.remetente == self.destinatario:
            raise ValidationError("O setor de origem não pode ser o mesmo que o setor de destino.")

    def save(self, *args, **kwargs):
        """
        Atualiza a última movimentação do processo ao salvar uma nova movimentação.
        """
        super().save(*args, **kwargs)
        self.processo.ultima_movimentacao = self
        self.processo.atual = self.destinatario
        self.processo.save()

class ProtocoloMovimentacao(models.Model):
    STATUS_CHOICES = [
        ('pendente', 'Pendente de Anexo'),

MGPROTOCOLO/templates/anexar_comprovacao.html
<div class="modal-content" hx-debug="true">
    <div class="modal-header justify-content-between">
        <h5 class="modal-title">Upload de Protocolo Assinado</h5>
    </div>
    <div class="modal-body">
    <form method="post" action="{% url 'anexar_comprovacao' protocolo.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        Anexar comprovante em PDF:
        {{ form.comprovacao }}
        <br>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
    </div>
</div>

MGPROTOCOLO/templates/correcao_processo_modal.html
<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Histórico de Correções - Processo {{ processo.numero }}</h5>
    </div>
    <div class="modal-body d-flex flex-row justify-content-between">
        <div class="col-5">
            <h6>Nova Correção</h6>
            <form hx-post="{% url 'salvar_correcoes_processo' processo.id %}" hx-target="#dialog" hx-swap="innerHTML">
            {% csrf_token %}
            {{ form.as_p }}
            {% if pode_modificar %}
                <button type="submit" class="btn btn-success">Salvar Alterações</button>
            {% else %}
                <div class="alert alert-warning" style="font-size:12px;">Você não pode editar este processo porque ele não está no seu setor.</div>
            {% endif %}
            </form>
        </div>
        <div class="col-6 table-responsive" style="max-height: 500px;">
            <table class="table table-striped">
                <tbody>
                    {% if correcoes %}
                        {% for correcao in correcoes %}
                            <tr>
                                <td style="font-size: 10px; text-align: left;">
                                    <strong>{{ correcao.get_campo_alterado_display }}:</strong> 
                                    "{{ correcao.valor_anterior }}" → "{{ correcao.valor_novo }}" <br>
                                    <small class="text-muted">Por {{ correcao.usuario.get_full_name }} em {{ correcao.data|date:"d/m/Y H:i" }}</small>
                                </td>
                            </tr>
                            {% endfor %}
                    {% else %}
                        <tr>
                            <td>
                                <p class="text-muted">Nenhuma correção registrada.</p>
                            </td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

MGPROTOCOLO/templates/criar_processo.html
{% extends 'base2.html' %}
{% block titulo %}Criar Processo{% endblock titulo %}
{% block contentdash %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="d-flex flex-column col-6">
                {{ form.non_field_errors }}
                <!-- DESCRIÇÃO -->
                <div class="mb-3">
                    <div class="d-flex flex-row justify-content-between align-items-center mb-1">
                        <label>Descrição:</label>
                        <a href="#"
                        class="btn btn-sm btn-secondary"
                        hx-get="{% url 'sugerir_dados_processo' %}"
                        hx-include="#id_descricao"
                        hx-target="#sugestao-descricao"
                        hx-indicator="#loading">
                        Buscar registros semelhantes
                        </a>
                    </div>
                    {{ form.descricao }}
                </div>
                <div class="d-flex flex-column mb-3">
                    <span>Número do Documento Motivador:</span>
                    <span style="font-size: x-small;">Não pode haver mais de um processo com o mesmo número de documento motivador/assunto.</span>
                    {{ form.numero }}
                </div>
                <div class="mb-3">
                    <span>Assunto:</span>
                    {{ form.titulo }}
                </div>
                <div class="d-flex flex-column mb-3">
                    <span>Setor fim:</span>
                    <span style="font-size: x-small;">O "setor fim" é utilizado pra que o destinatário final possa saber com antecedência que um documento destinado a ele está tramitando em outros setores.</span>
                    {{ form.fim }}
                </div>
                <div class="d-flex flex-column mb-3">
                    <span>Forma de tramitação:</span>
                    <span style="font-size: x-small;">Selecione "Digital" caso não pretenda enviar nenhum documento fisico (impresso) para circular entre os setores. Processos digitais costumam circular de forma mais ágil.</span>
                    {{ form.modalidade }}
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
            <div class="col-6">
                <div class="d-flex justify-content-between align-items-center">
                    <h6>Sugestões de preenchimento</h6>
                </div>
                <hr>
                <small id="sugestao-descricao" class="text-muted d-block mt-1"></small>
                <span id="loading" style="display:none;">🔄 Sugerindo...</span>
            </div>
        </div>
    </form>

    <script>
        function preencherCampos(numero, titulo, descricao, fim_id) {
            document.getElementById("id_numero").value = numero;
            document.getElementById("id_titulo").value = titulo;
            document.getElementById("id_descricao").value = descricao;
            document.getElementById("id_fim").value = fim_id;
        }
    </script>
{% endblock %}

MGPROTOCOLO/templates/detalhes_processo.html
{% extends 'base2.html' %}
{% block titulo %}Detalhes do Processo{% endblock titulo %}
{% block contentdash %}
   <!-- Cabeçalho com Informações Básicas do Processo -->
   <div class="row">
        <div class="col">
            <div class="card mb-2">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="col-7">
                            <p class="card-title"><b>{{ processo.numero }} - {{ processo.titulo }}</b></p>
                            <div style="margin: 0; padding: 0; font-size: small;">
                                <li style="list-style-type: None;">{{ processo.descricao }}</li>
                            </div>
                        </div>
                        <div class="col-2 btn-group-vertical">
                            <button class="btn btn-secondary" hx-get="{% url 'mais_informacoes' processo.id %}" hx-target="#dialog" hx-trigger="click">
                                <i class="lni lni-info"></i> Mais Informações
                            </button>
                            <button class="btn btn-light" hx-get="{% url 'historico_correcoes_processo' processo.id %}" hx-target="#dialog2" hx-trigger="click">
                                <i class="lni lni-info"></i> Correções
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if not pode_modificar %}
        <div class="d-flex justify-content-center mb-2">
            <small class="badge bg-secondary">Este processo está {{ processo.get_status_display|lower }} no setor {{ processo.setor_atual|title }}</small> 
        </div>
    {% endif %}
    <!-- Duas Colunas: Documentos e Movimentações -->
    <div class="row">
        <!-- Coluna da Esquerda: Documentos -->
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <h5 class="card-title mb-0">Documentos</h5> 
                        {% if pode_modificar %}
                            <a type="button" class="btn btn-sm btn-info py-0" hx-get="{% url 'criar_documento' processo.id %}" hx-target="#dialog">
                                + Adicionar Documento
                            </a>
                        {% endif %}
                    </div>
                    
                </div>
                <div class="card-body">
                    {% if processo.documentos.all %}
                        <div class="list-group">
                            {% for documento in processo.documentos.all|dictsortreversed:"criado_em" %}
                                <div class="list-group-item">
                                    <div class="d-flex flex-row justify-content-between align-items-center" style="font-size: small;">
                                        <div class="d-flex flex-column">
                                            <p class="mb-0">{{ documento.descricao }}</p>
                                            <small class="text-muted">Incluído por {{ documento.criado_por.get_full_name }} em {{ documento.criado_em|date:"d/m/Y H:i" }}</small>
                                            <small class="text-muted">{{ documento.get_tipo_display }} - {{ documento.get_classificacao_display }}</small>    
                                        </div>
                                        <div>
                                            <a href="{% if documento.arquivo %}{{ documento.arquivo.url }}{% endif %}" class="btn btn-sm btn-outline-primary mx-1" target="_blank">
                                                <i class="lni lni-download"></i> Baixar
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p class="text-muted">Nenhum documento encontrado.</p>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- Coluna da Direita: Movimentações -->
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <h5 class="card-title mb-0">Movimentações</h5> 
                        <div class="flex-row">
                            {% if pode_modificar %}
                                {% if processo.ultima_movimentacao.status == 'em_tramitacao' and processo.ultima_movimentacao.confirmacao == 'pendente' %}
                                    <form method="post" action="{% url 'receber_processo' processo.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-sm btn-warning">Receber</button>
                                    </form>
                                {% else %}
                                    <a type="button" class="btn btn-sm btn-warning py-0" hx-get="{% url 'criar_movimentacao' processo.id %}" hx-target="#dialog">
                                        + Criar Movimentação
                                    </a>
                                {% endif %}
                            {% endif %}
                            <a type="button" class="btn btn-sm btn-info py-0" href="{% url 'gerar_historico_tramitacoes' processo.id %}">Tramitações <i class="fa-solid fa-print"></i></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    {% if processo.movimentacoes.all %}
                        <div class="list-group">
                            {% for movimentacao in processo.movimentacoes.all|dictsortreversed:"realizado_em" %}
                                <div class="list-group-item">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="col-9 d-flex flex-column" style="font-size: small;">
                                            <p class="m-0">
                                                {% if movimentacao.destinatario.sigla == 'ARQ' %}
                                                    <i class="lni lni-archive"></i> Arquivado por {{ movimentacao.remetente.nome }}
                                                {% else %}
                                                    De {{ movimentacao.remetente.nome }} para {{ movimentacao.destinatario.nome }}
                                                {% endif %}
                                            </p>
                                            <small class="text-muted">
                                                Enviada por {{ movimentacao.realizado_por.get_full_name }} em {{ movimentacao.realizado_em|date:"d/m/Y H:i" }}
                                            </small>
                                            {% if movimentacao.descricao %}
                                                <small class="text-muted">
                                                    Anotação: {{ movimentacao.descricao}}
                                                </small>
                                                {% endif %}
                                            {% if movimentacao.status == 'recebida' and movimentacao.destinatario.sigla != 'ARQ'%}
                                                {% if movimentacao.confirmacao == 'manual' %}
                                                    <small class="text-muted">
                                                        <a type="button" style="text-decoration: none;" hx-get="{% url 'visualizar_comprovacao' movimentacao.protocolos.first.id %}" hx-target="#dialog" hx-trigger="click" data-bs-toggle="modal" data-bs-target="#modal">Confirmado manualmente em {{ movimentacao.realizado_em|date:"d/m/Y H:i" }}
                                                        (Visualizar)</a>
                                                    </small>
                                                {% else %}
                                                    <small class="text-muted">
                                                        Recebida por {{ movimentacao.confirmado_por.get_full_name}} em {{ movimentacao.confirmado_em|date:"d/m/Y H:i" }}
                                                    </small>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                        <div class="col-3 d-flex justify-content-center">
                                            {% if movimentacao.destinatario.sigla == 'ARQ' %}
                                                <span class="badge bg-dark">
                                                    Arquivado
                                                </span>
                                            {% else %}
                                                <span class="badge bg-{% if movimentacao.status == 'recebida' %}success{% else %}info{% endif %}">
                                                    {{ movimentacao.get_status_display }}
                                                </span>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p class="text-muted">Nenhuma movimentação encontrada.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}