MGC/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='mgc'),
    #path('configuracoes/', views.configuracoes, name='configuracoes'),

    # path('processos/', views.processos, name='processos'),
    # path('processos/adicionar/', views.processos_add, name='processos_add'),
    # path('processos/adicionar/licon', views.licitacao_request, name='licitacao_request'),
    # path('processos/editar/<int:processo_pk>', views.processos_edit, name='processo_edit'),
    # path('processos/deletar/<int:processo_pk>', views.processos_delet, name='processo_delet'),

    path('contratos/', views.contratos, name='contratos'), #VISUALIZAR TODOS OS CONTRATOS
    # path('contratos/adicionar/<int:processo_pk>/', views.contratos_add, name='contratos_add'),
    path('contratos/addsaldosec/<int:contrato_pk>/', views.contratos_addsaldosec, name='contrato_addsaldo'),
    path('contratos/additens/<int:contrato_pk>/', views.contratos_additens, name='contratos_additens'),
    # path('contratos/anexarof/<int:contrato_pk>/', views.contrato_enviar, name='contrato_enviar'), #ADAPTAR PARA ORDENS/ANEXAR
    # path('contratos/editar/<int:contrato_pk>', views.contrato_edit, name='contrato_edit'),
    # path('contratos/deletar/<int:contrato_pk>', views.contrato_delet, name='contrato_delet'),

    path('contratos/ordens/', views.ordens, name='ordens'),
    path('contratos/ordens/detalhes/<int:saldodetalhes_pk>/', views.saldo_detalhes, name='saldo_detalhes'),
    path('contratos/ordens/detalhes/<int:saldodetalhes_pk>/emitir', views.of_emitir, name='of_emitir'),

    path('contratos/ordens/detalhes/<int:saldoof_pk>/<int:of_log_pk>', views.of_log_delet, name='of_log_delet'),
    path('contratos/ordens/editar/<int:saldoof_pk>', views.of_edit, name='of_edit'),
    #path('contratos/ordens/deletar/<int:saldoof_pk>', views.of_delet, name='of_delet'),

    path('contratos/fiscal/', views.painelfiscal, name='painelfiscal'),

    path('contratos/adicionar', views.add_contratos, name='add_contratos'),
    path('contratos/editar/<int:contrato_id>', views.edit_contrato, name='edit_contrato'),
    path('contratos/request', views.contratos_request, name='contratos_request'),
    path('contratos/resquest/processar', views.processar_contratos_selecionados, name='processar_contratos_selecionados'),

    path('fornecedor/editar/<int:saldocontratosec_id>', views.confirmar_fornecedor, name='confirmar_fornecedor'),

    path('saldosec/<int:saldocontratosec_id>/exportar_excel/', views.exportar_excel_saldo, name='exportar_excel_saldo'),

    path('emitirof', views.emitirOF, name='emitirof'),

    #### HTMX ###########

    path('contratosbase/', views.contratos_base, name='contratos_base'),

    
    
]

MGCOMBUSTIVEIS/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashcombustiveis, name='dashcombustiveis'),
    path('abastecimentos/', views.abastecimentos, name='abastecimentos'),
    path('abastecimentos/list', views.abastecimentos_list, name='abastecimentos_list'),
    path('abastecimentos/add', views.add_abastecimento, name='add_abastecimento'),
    path('abastecimentos/<int:abastecimento_pk>/edit', views.edit_abastecimento, name='edit_abastecimento'),
    path('frota/', views.frota, name='frota'),
    path('frota/list', views.frota_list, name='frota_list'),
    path('frota/add', views.add_frota, name='add_frota'),
    path('frota/<int:frota_pk>/edit', views.edit_frota, name='edit_frota'),
    path('condutores/', views.condutores, name='condutores'),
    path('condutores/list', views.condutores_list, name='condutores_list'),
    path('condutores/add', views.add_condutores, name='add_condutores'),
    path('condutores/<int:condutor_pk>/edit', views.edit_condutores, name='edit_condutores'),
    path('relatorios/', views.emitir_relatorio, name='emitir_relatorio'),
]

SGI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('HOME.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('gestaocontratos/',include('MGC.urls')),
    path('combustiveis/',include('MGCOMBUSTIVEIS.urls')),
    path('regularidadefiscal/',include('MGREGULARIDADEFISCAL.urls')),
    path('protocolo/',include('MGPROTOCOLO.urls')),
    path('transparencia/',include('MGTRANSPARENCIA.urls')),
    path('comunicacao/',include('MGCOMUNICACAO.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MGCOMBUSTIVEIS/models.py
from django.db import models
from django.contrib.auth.models import Group, User
from HOME.models import Secretaria

class veiculo(models.Model):

    placa = models.CharField(max_length=8)
    ano = models.IntegerField(null=True, blank=True)
    modelo = models.CharField(max_length=100, null=True, blank=True)
    secretaria = models.ForeignKey(Secretaria, on_delete=models.PROTECT)
    descricao = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=60, choices=[('Em atividade','Em atividade'),('Em manutenção','Em manutenção'),('Excluído da frota','Excluído da frota')])
    observacao = models.TextField(null=True, blank=True)
    propriedade = models.CharField(max_length=60, choices=[('Próprio','Próprio'),('Contratado','Contratado')])

    def __str__(self):
        return f'{self.placa} - {self.modelo} - {self.secretaria}'

class fiscal (models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return f'{self.nome}'

class condutor (models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=30, null=True, blank=True)
    datanascimento = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=30, choices=[('Ativo','Ativo'),('Desligado','Desligado')], default='Ativo')
    validadeCNH = models.DateField(null=True,blank=True)
    categoriaCNH = models.CharField(max_length=2, null=True, blank=True)
    cursoEscolar = models.BooleanField(default=False)
    observacoes = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.nome}'

class Abastecimentos (models.Model):

    tipo_combustiveis = [
        ('Gasolina','Gasolina'),
        ('Diesel Comum','Diesel Comum'),
        ('Diesel S-10','Diesel S-10'),
        ('GNV','GNV'),
        ('Etanol','Etanol'),
    ]

    status_choice = [
        ('Aprovado','Aprovado'),
        ('Pendente','Pendente'),
        ('Negado','Negado'),
    ]
    data = models.DateField(null=True)
    veiculo = models.ForeignKey(veiculo, on_delete=models.PROTECT)
    tipo = models.CharField(max_length=30,choices=tipo_combustiveis)
    quantidade = models.FloatField(null=True)
    valorUnitario = models.FloatField(null=True)
    valorTotal = models.FloatField(null=True)
    condutor = models.ForeignKey(condutor, on_delete=models.PROTECT)
    fiscal = models.ForeignKey(fiscal, on_delete=models.PROTECT)
    km = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=10,choices=status_choice,default='Pendente')

    def __str__(self):
        return f'{self.veiculo.placa} - {self.data} - {self.tipo} - R${self.valorTotal}'

MGCOMBUSTIVEIS/views.py
import base64
from collections import defaultdict
from datetime import date, datetime, timedelta
import json
from django.http import HttpResponse
from django.shortcuts import redirect, render
from weasyprint import HTML
from . import models, forms
from django.core.paginator import Paginator
from . import models
from django.db.models import Count, Sum
from django.template.loader import render_to_string
from django.db.models.functions import ExtractMonth

def dashcombustiveis(request):
    
    # Resumo geral
    total_veiculos = models.veiculo.objects.count()
    total_condutores = models.condutor.objects.count()
    total_abastecimentos = models.Abastecimentos.objects.count()

    # Gráficos
    veiculos_secretaria = models.veiculo.objects.values('secretaria__nome').annotate(total=Count('id'))
    veiculos_secretaria_labels = [v['secretaria__nome'] for v in veiculos_secretaria]  # Usando secretaria__nome
    veiculos_secretaria_data = [v['total'] for v in veiculos_secretaria]

    consumo_meses = models.Abastecimentos.objects.filter(
        data__gte=date.today() - timedelta(days=180)
    ).annotate(mes=ExtractMonth('data')).values('mes').annotate(total=Sum('quantidade'))

    consumo_meses_labels = [f"Mês {c['mes']}" for c in consumo_meses]
    consumo_meses_data = [c['total'] for c in consumo_meses]

    # Tabelas
    ultimos_abastecimentos = models.Abastecimentos.objects.order_by('-data')[:5]
    cnh_vencendo = models.condutor.objects.filter(validadeCNH__lte=date.today() + timedelta(days=180))

    context = {
        'total_veiculos': total_veiculos,
        'total_condutores': total_condutores,
        'total_abastecimentos': total_abastecimentos,
        'veiculos_secretaria_labels': veiculos_secretaria_labels,
        'veiculos_secretaria_data': veiculos_secretaria_data,
        'consumo_meses_labels': consumo_meses_labels,
        'consumo_meses_data': consumo_meses_data,
        'ultimos_abastecimentos': ultimos_abastecimentos,
        'cnh_vencendo': cnh_vencendo,
    }

    return render (request,'dashcombustiveis.html',context)

#-------------- ABASTECIMENTOS -----------------------#
def abastecimentos(request):
    return render (request,'abastecimentos/abastecimentos.html',{})

def abastecimentos_list(request):
    # buscar = request.GET.get('buscar')
    # if buscar:
    #     abastecimentos = models.Abastecimentos.objects.filter(veiculo__placa__icontains = buscar)
    # else:
    abastecimentos = models.Abastecimentos.objects.all().order_by('-data')
    return render(request, 'abastecimentos/abastecimentos_list.html', {'abastecimentos': abastecimentos})

def add_abastecimento(request):
    if request.method == "POST":
        form = forms.Abastecimentos_form(request.POST or None)
        def truncate_float(value, digits_after_point=2):
            pow_10 = 10 ** digits_after_point
            return (float(int(value * pow_10)))/pow_10

        if form.is_valid():
            form.save(commit=False)
            form.instance.valorTotal = truncate_float(form.instance.valorUnitario * form.instance.quantidade)
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "AbastecimentosListChanged": None,
                        "showMessage": f"Abastecimento registrado!"
                    })
                })
        else:
            return render(request, 'abastecimentos/abastecimentos_form.html', {
                'form': form,
            })
    else:
        form = forms.Abastecimentos_form()
    return render(request, 'abastecimentos/abastecimentos_form.html', {
        'form': form,
    })

def edit_abastecimento(request, abastecimento_pk):
    abastecimento_instance = models.Abastecimentos.objects.get(pk = abastecimento_pk)
    form = forms.Abastecimentos_form(request.POST or None, instance = abastecimento_instance)
    if request.POST:
        if form.is_valid:
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "AbastecimentosListChanged": None,
                        "showMessage": f"Abastecimento editado com sucesso!"
                    })
                })
        else:
            return render(request, 'abastecimentos/abastecimentos_form.html', {
                'form': form,
            })

    return render (request, 'abastecimentos/abastecimentos_form.html', {
        'form':form,
    })

#-------------- FROTA --------------------------------#
def frota(request):
    return render (request,'frota/frota.html',{})

def frota_list(request):
    frota = models.veiculo.objects.all()
    return render(request, 'frota/frota_list.html', {'frota': frota})

def add_frota(request):
    if request.method == "POST":
        form = forms.Frota_form(request.POST or None)
        print(form.is_valid())
        if form.is_valid():
            # ALTERAR A PARTIR DAQUI
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "FrotaListChanged": None,
                        "showMessage": f"Veículo registrado!"
                    })
                })
        else:
            return render(request, 'frota/frota_form.html', {
                'form': form,
            })
    else:
        form = forms.Frota_form()
    return render(request, 'frota/frota_form.html', {
        'form': form,
    })

def edit_frota(request, frota_pk):
    frota_instance = models.veiculo.objects.get(pk = frota_pk)
    form = forms.Frota_form(request.POST or None, instance = frota_instance)
    if request.POST:
        if form.is_valid:
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "FrotaListChanged": None,
                        "showMessage": f"Veículo editado com sucesso!"
                    })
                })
        else:
            return render(request, 'frota/frota_form.html', {
                'form': form,
            })

    return render (request, 'frota/frota_form.html', {
        'form':form,
    })

#-------------- CONDUTORES --------------------------------#
def condutores(request):
    return render (request,'condutores/condutores.html',{})

def condutores_list(request):
    condutores = models.condutor.objects.all()
    return render(request, 'condutores/condutores_list.html', {'condutores': condutores})

def add_condutores(request):
    if request.method == "POST":
        form = forms.Condutores_form(request.POST or None)
        if form.is_valid():
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "CondutoresListChanged": None,
                        "showMessage": f"Condutor registrado!"
                    })
                })
        else:
            return render(request, 'condutores/condutores_form.html', {
                'form': form,
            })
    else:
        form = forms.Condutores_form()
    return render(request, 'condutores/condutores_form.html', {
        'form': form,
    })

def edit_condutores(request, condutor_pk):
    condutores_instance = models.condutor.objects.get(pk = condutor_pk)
    form = forms.Condutores_form(request.POST or None, instance = condutores_instance)
    if request.POST:
        if form.is_valid:
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "CondutoresListChanged": None,
                        "showMessage": f"Condutor editado com sucesso!"
                    })
                })
        else:
            return render(request, 'condutores/condutores_form.html', {
                'form': form,
            })

    return render (request, 'condutores/condutores_form.html', {
        'form':form,
    })

def emitir_relatorio(request):

    # Consultar opções para os filtros
    veiculos = models.veiculo.objects.all()
    condutores = models.condutor.objects.all()
    secretarias = models.veiculo.objects.values_list('secretaria', flat=True).distinct()

    with open("static/img/bg-timbrado-logo.png", "rb") as image_file:
                page_background = base64.b64encode(image_file.read()).decode('utf-8')

    if request.method == "POST":
        tipo_relatorio = request.POST.get("tipo_relatorio")

        # Obter a data atual para o cabeçalho
        agora = datetime.now()

        if tipo_relatorio == "abastecimento":
            # Filtros para abastecimentos
            veiculo_id = request.POST.get("veiculo")
            condutor_id = request.POST.get("condutor")
            periodo_inicio = request.POST.get("periodo_inicio")
            periodo_fim = request.POST.get("periodo_fim")
            status = request.POST.get("status")
            tipo_combustivel = request.POST.get("tipo_combustivel")

            abastecimentos = models.Abastecimentos.objects.all().order_by('veiculo', 'data')
            print('Abastecimentos:')
            print(abastecimentos)
        
            # Aplicar os filtros, se existirem
            if veiculo_id:
                abastecimentos = abastecimentos.filter(veiculo__id=veiculo_id)
            if condutor_id:
                abastecimentos = abastecimentos.filter(condutor__id=condutor_id)
            if periodo_inicio:
                abastecimentos = abastecimentos.filter(data__gte=periodo_inicio)
            if periodo_fim:
                abastecimentos = abastecimentos.filter(data__lte=periodo_fim)
            if status:
                abastecimentos = abastecimentos.filter(status=status)
            if tipo_combustivel:

MGCOMBUSTIVEIS/templates/frota/frota.html
{% extends "base2.html" %}

{% block head_title %} Frota {% endblock head_title %}

{% block contentdash %}
    <div class="d-flex justify-content-between">
            <h4><b>SGI</b> - Frota</h4>
            <a type="button" class="btn btn-success" hx-get="{% url 'add_frota' %}" hx-target="#dialog"><i class="lni lni-plus"></i> Registrar Veículo</a>
    </div>
    <hr>
    <!-- <form class="form-inline" action="." method="get">
        <div class="row container-fluid ">
            <div class="col-sm-4">
                <input type="text" id="buscar" name="buscar" class="form-group form-control" placeholder="Placa, Modelo, Ano...">
            </div>
            <div class="col">
                <input type="submit" class="btn btn-primary form-group" value="Buscar">
            </div>
        </div>
    </form> -->
    <div class="table-responsive" style="max-height: 80vh;">
        <table class="table table-sm table-striped">
            <thead>
                <tr>
                    <th scope="col">Placa</th>
                    <th scope="col">Modelo</th>
                    <th scope="col">Ano</th>
                    <th scope="col">Secretaria</th>
                    <th scope="col">Status</th>
                    <th scope="col">Propriedade</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>

            <tbody hx-trigger="load, FrotaListChanged from:body" hx-get="{% url 'frota_list' %}" hx-target="this">
                <tr>
                  <td class="spinner-border" role="status">
                    <span class="visually-hidden">Carregando...</span>
                  </td>
                </tr>
            </tbody>
        </table>
    </div>
    
    <div class="wrapper justify-content-center">
        <nav aria-label="Page navigation">
            <ul class="pagination pagination-sm">

                {% if frota.has_previous %}
                    <li class="page-item">

                        {% if request.GET.buscar %}
                            <a class="page-link" href="?page=1&buscar={{request.GET.buscar}}" aria-label="Anterior">
                        {% else %}
                            <a class="page-link" href="?page=1" aria-label="Anterior">
                        {% endif %}
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Primeira</span>
                        </a>
                    </li>   
                {% endif %}
            
                {% for n in frota.paginator.page_range %}

                    {% if frota.number == n %}
                        <li class="page-item active">
                            <span class="page-link">{{ n }}</span>
                        </li>
                    {% elif n > frota.number|add:'-3' and n < frota.number|add:'3' %}
                        {% if request.GET.buscar %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}&buscar={{request.GET.buscar}}">{{ n }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                        {% endif %}
                    {% endif %}



                {% endfor %}
            
                {% if frota.has_next %}
                    <li class="page-item">
                        {% if request.GET.buscar %}
                            <a class="page-link" href="?page={{ frota.paginator.num_pages }}&buscar={{request.GET.buscar}}" aria-label="Próxima">
                        {% else %}
                            <a class="page-link" href="?page={{ frota.paginator.num_pages }}" aria-label="Próxima">
                        {% endif %}
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Última</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>    
{% endblock contentdash %}

MGCOMBUSTIVEIS/templates/frota/frota_edit.html
{% extends "base.html" %}

{% block head_title %} Contratos {% endblock head_title %}

{% block contentdash %}
    <div class="d-flex justify-content-between">
        <h4><b>CONTRATOS - </b>Editar</h4>
    </div>
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ contratos_form.as_p }}
        <div>
            <button type="submit" class="btn btn-success">Salvar</button>
            <a href="{% url 'contratos' %}" class="btn btn-danger">Cancelar</a>
        </div>
    </form>
{% endblock contentdash %}

MGCOMBUSTIVEIS/templates/frota/frota_form.html
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Informações do Veículo</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <div class="mb-3">
          <div class="row g-3">
            <div class="col-md-6">
                <label for="placa" class="form-label">Placa</label>
                {{form.placa}}
            </div>
            <div class="col-md-6">
                <label for="id_ano" class="form-label">Ano</label>
                {{form.ano}}
            </div>
            <div class="col-md-6">
                <label for="id_modelo" class="form-label">Modelo</label>
                {{form.modelo}}
            </div>
            <div class="col-md-6">
                <label for="id_secretaria" class="form-label">Secretaria</label>
                {{form.secretaria}}
            </div>
            <div class="col-md-12">
                <label for="id_descricao" class="form-label">Descrição</label>
                {{form.descricao}}
            </div>
            <div class="col-md-6">
                <label for="id_status" class="form-label">Status</label>
                {{form.status}}
            </div>
            <div class="col-md-6">
                <label for="id_propriedade" class="form-label">Propriedade</label>
                {{form.propriedade}}
            </div>
            <div class="col-md-12">
                <label for="observacao" class="form-label">Observações</label>
                {{form.observacao}}
            </div>
        </div>            
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
        Cancelar
      </button>
      <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
  </form>

MGCOMBUSTIVEIS/templates/frota/frota_list.html
{% for veiculo in frota %}
    <tr>
        <td>{{ veiculo.placa }}</td>
        <td>{{ veiculo.modelo }}</td>
        <td>{{ veiculo.ano }}</td>
        <td>{{ veiculo.secretaria }}</td>
        <td>{{ veiculo.status }}</td>
        <td>{{ veiculo.propriedade }}</td>
        <td>
            <div class='btn-group btn-group-sm' role='group'>
                <a hx-get="{% url 'edit_frota' veiculo.pk %}" hx-target="#dialog" class="btn btn-secondary"><i class="lni lni-pencil-alt"></i></a>
            </div>
        </td>
    </tr>
{% endfor %}